name: inventory_app
description: QR-Based Inventory & Sales Tracking App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.0
  printing: ^5.11.1
  pdf: ^3.10.7
  intl: ^0.19.0
  fl_chart: ^1.2.0
  simple_barcode_scanner: ^0.6.0
  barcode_widget: ^2.0.4
  share_plus: ^13.3.0
  path_provider: ^2.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
